### ISSUE TITLE
Balance considerations

### ISSUE THREAD

**Issue by Darkmega18** [klipsey/SeamstressMod#4]
So I played the character for a little while and found some things to poke at for balance.

Firstly: Her weapons when thrown out, you're meant to be able to pick them up to slash, however for what can sometimes be a fairly hectic game the weapons take a considerable amount of time to become "active" so you can pick them up again. Can you make them become active quicker? Like say maybe 2 seconds after direct impact/sticking into an enemy?

Perhaps there could also be no automatic collection/cooling down of the weapons and instead casting the skill towards a weapon's area in view will dash you to it within a certain distance and immediately pick it up (prioritized over throwing your second weapon if it's not out yet)? but then after say 6-8 seconds of not having your weapons you can cast a recall skill that will despawn them and bring them back to you reloading the charges.

Her blink. In my game it doesn't seem to dash upwards much if at all UNLESS I stand still, then she basically jumps on the spot a short distance. it also feels very short in general.
Can you improve it's ability to go upwards and towards the cursor? sort of like using huntress's normal blink but with the distance of a phase blink? Similar if you have needles you should then be able to just hop across the sky repeatedly using these directional phase blinks.

Planar manipulation is a very cool ability, but I find it's potentially cumbersome to use to lift up and then slam a foe. the slam also doesn't occur if you just let them go as they reach velocity to impact a surface (I also didn't try smacking them into surfaces sideways etc). 
Would you be able to leave a lingering effect on the foe while they're grasped by the swirling effect it places on them so that when they impact surfaces while still moving at a significant enough speed they'll still detonate properly without needing to hold the ability on them the entire time so it can be a bit more snappy to use?
Further, it's generally ineffective on large foes. Can I suggest a synergy with her kit where if you manage to stick a symbiotic weapon into a larger foe (oil gunner, construct etc) you can lift them up at a significantly faster/stronger level because you instead levitate the weapon thats stuck inside them? Could be fun to be able to stick both weapons into a large boss and be able to lift them and smash them.
A secondary effect to this you could add is that if you slam a foe who has a symbiotic weapon in them when they impact a surface the blast radius will also "sweep" the weapon for you and retrieve it along with their detonation, but when retrieved in this way maybe for balance don't generate a needle, since it costs needles to use the skill in the first place.

Thats what I got for now.

**Comment by klipsey** [comment]
Unfathomable skill issue unfortunately

**Comment by Darkmega18** [comment]
I give you suggestions and even synergy ideas and thats all you can say? 
how unfathomably rude more like.

**Comment by klipsey** [comment]
I don't have the time to answer every persons suggestions or complaints especially when a majority of it is simply a lack of experimenting with the character like yours. Everything you have issues with is entirely user error and a lack of knowledge. 1. cooldown reduction lowers pickup time, you also generally want to keep the scissors off you for the attackspeed bonus and needle gain. 2. It literally blinks towards your cursor when moving forward, check your config to see if you have the ground blink angle screwed up 3. You didn't even try slamming them into a wall? Really? Also, you don't even need to hold them the entire time, smoothly and quickly moving your crosshair in a direction then letting go will already do this. If you want to pick up large enemies, go to your config and enable it. Otherwise slam smaller enemies into the boss, the damage is aoe. The ability doesn't even cost a needle, it deals more damage with needles lmao.
